import { createElement } from 'lwc';
import ContactArrayInfoSunday3 from 'c/contactArrayInfoSunday3';

describe('c-contact-array-info-sunday3', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-contact-array-info-sunday3', {
            is: ContactArrayInfoSunday3
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});