Candidates.companyName = 'Sofinnovas';
Candidates.printCandidateInfoSt();

Candidates c1 = new Candidates();
c1.name = 'Jerry';
c1.gender ='Male';
c1.printCandidate();

Candidates c2 = new Candidates();
c2.name = 'Elanie';
c2.gender = 'Female';
c2.printCandidate();

Candidates c3 = new Candidates();
c3.name = 'Burcu';
c3.gender = 'Female';
c3.printCandidate();

Candidates.companyName = 'SOFTINNOVAS INC.';
c1.printCandidate();
c2.printCandidate();
c3.printCandidate();

