ListDemo1.candidatesList();
ListDemo1.randomIntegerList();

// string s2 = ListDemo1.candidatesList(2);
// system.debug(s2);
system.debug(ListDemo1.candidatesList(2));
system.debug(ListDemo1.candidatesList(5));
system.debug(ListDemo1.candidatesList(-5));
// string s5 = ListDemo1.candidatesList(5);
// system.debug(s5);

// string s_1 = ListDemo1.candidatesList(-5);
// system.debug(s_1);

ListDemo1.allCats();

ListDemo1.allCars();

ListDemo1.iterateIntegerList();