LoopDemo ld = new LoopDemo();
ld.print_sum_N_Numbers(25);
ld.print_int_while();
ld.print_N_Numbers_2(5);
ld.print_N_Numbers(20);

LoopDemo ld3 = new LoopDemo();
ld3.print_N_Odd_numbers(4, 94);

//burak hocayla yaptigimiz ornekler
string a;
a += 'word';
system.debug(a);

// integer b;  //bunun baslangic degeri olmadigi icin hata verdi
// b += 5;
// system.debug(b);

integer c =0;   //ama burda 0 dan baslattigimiz icin uzerine 5 ekleyebildi.
c += 5;
system.debug(c);